# Generated by Django 2.2.3 on 2019-07-23 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.CharField(max_length=500)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('address', models.CharField(max_length=300)),
                ('capacity', models.PositiveIntegerField()),
                ('availability', models.BooleanField(default=True)),
                ('picture', models.CharField(max_length=500)),
                ('price', models.PositiveIntegerField()),
                ('length', models.FloatField()),
                ('width', models.FloatField()),
                ('heated', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('OUTDOOR', 'Outdoor'), ('INDOOR', 'Indoor'), ('COVERED', 'Covered')], max_length=100)),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent.Profil')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent.Pool')),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent.Profil')),
            ],
        ),
    ]
