# Generated by Django 2.2.3 on 2019-07-23 20:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rent', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profil',
            new_name='UserProfile',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='profil',
            new_name='user_profile',
        ),
        migrations.RenameField(
            model_name='pool',
            old_name='profil',
            new_name='user_profile',
        ),
    ]
