# Generated by Django 2.2.3 on 2019-07-24 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0003_auto_20190724_0908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pool',
            name='type',
        ),
    ]
