# Generated by Django 2.2.3 on 2019-07-24 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0004_remove_pool_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='pool',
            name='type',
            field=models.CharField(choices=[('OUTDOOR', 'Outdoor'), ('INDOOR', 'Indoor'), ('COVERED', 'Covered')], default='OUTDOOR', max_length=100),
        ),
    ]
