# Generated by Django 2.2.3 on 2019-07-26 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0006_auto_20190726_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pool',
            name='image',
            field=models.ImageField(blank=True, upload_to='pool_images'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, upload_to='profile_images'),
        ),
    ]
