# Generated by Django 2.2.3 on 2019-07-28 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0007_auto_20190726_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='participants',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
