# Generated by Django 2.2.3 on 2019-07-30 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0008_booking_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pool',
            name='image',
            field=models.FileField(blank=True, upload_to='pool_images'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.FileField(blank=True, upload_to='profile_images'),
        ),
    ]
